// cSpell: ignore PTHC

/**
 * This holds all the female hero slaves that have hyper pregnancy.
 * See instructions in `slaveDatabase_000-instructions.md` for how to add to these databases.
 * Valid IDs start at 904001 and end at 906000.
 * @type {FC.HeroSlaveTemplate[]}
 */
App.Data.HeroSlaves.XXHyperPreg = [
	{
		/* Added prestige and career to match origin. Heavily edited origin for grammar and semantics. -DerangedLonger */
		ID: 904001,
		slaveName: "'PTHC' Cecily",
		slaveSurname: "Bóndi",
		birthName: "Cecily",
		birthSurname: (V.realRoyalties === 1 ? "Windsor" : 0),
		origin: "Kidnapped from a royal family and held for ransom, $he was unloaded on the open market after $his family failed to pay in full in an effort to minimize costs. Impressed by $his royal linage, a wealthy arcology owner was more than happy to snatch her up as his slave. $He was used as part of his elite breeding program, and after many children, put up for sale as a prime broodmother to limit the influence of $his genes in that arcology.",
		prestige: 2,
		prestigeDesc: "$His royal blood makes $him especially desirable as a broodmother.",
		actualAge: 17,
		visualAge: 17,
		physicalAge: 17,
		ovaryAge: 17,
		health: {condition: 60},
		trust: 65,
		devotion: 65,
		weight: 25,
		muscles: 40,
		height: 164,
		nationality: "British",
		race: "white",
		eye: {origColor: "light grey"},
		origHColor: "amber",
		origSkin: "fair",
		hLength: 100,
		hStyle: "crown braid",
		pubicHStyle: "waxed",
		underArmHStyle: "waxed",
		waist: -35,
		voice: 3,
		shoulders: -1,
		boobs: 2300,
		boobShape: "torpedo-shaped",
		nipples: "huge",
		lactation:1,
		lactationDuration: 2,
		lactationAdaptation: 70,
		hips: 2,
		butt: 4,
		face: 100,
		faceImplant: 5,
		faceShape: "cute",
		lips: 25,
		vagina: 1,
		vaginaLube: 2,
		preg: -1,
		pregAdaptation: 100,
		foreskin: 3,
		anus: 1,
		analArea: 2,
		ovaries: 1,
		makeup: 1,
		nails: 9,
		piercing: {nose: {weight: 1}},
		intelligence: 75,
		intelligenceImplant: 15,
		energy: 90,
		attrXX: 55,
		attrXY: 80,
		fetish: "buttslut",
		fetishStrength: 100,
		fetishKnown: 1,
		behavioralQuirk: "cutting",
		sexualQuirk: "painal queen",
		counter: {birthsTotal: 105},
		skill: {
			vaginal: 100, oral: 65, anal: 35, servant: 100
		},
		geneMods: {rapidCellGrowth: 1, progenitor: 1},
		natural: {height: 165, boobs: 400},
		career: "a princess"
	},
	{
		/* Unlike Cecily, she's cheap enough to show up in arcology acquisition. -DerangedLonger */
		ID: 904002,
		slaveName: "'Mother' Thérèse",
		birthName: "Thérèse",
		origin: "$His life was undistinguished, until someone discovered $he was quite intelligent and had a genetic mutation that made her hyperfertile.",
		actualAge: 25,
		visualAge: 25,
		physicalAge: 25,
		ovaryAge: 25,
		health: {condition: 60},
		trust: 15,
		devotion: 35,
		weight: 20,
		muscles: 25,
		height: 158,
		nationality: "French",
		race: "white",
		accent: 1,
		eye: {origColor: "blue"},
		origHColor: "golden",
		origSkin: "fair",
		markings: "freckles",
		hLength: 30,
		hStyle: "ponytail",
		underArmHStyle: "shaved",
		waist: -25,
		voice: 2,
		shoulders: -1,
		boobs: 750,
		natural: {boobs: 500},
		boobShape: "normal",
		nipples: "huge",
		lactationAdaptation: 55,
		hips: 2,
		butt: 5,
		face: 70,
		faceShape: "cute",
		lips: 25,
		vagina: 1,
		vaginaLube: 1,
		preg: -1,
		pregAdaptation: 70,
		anus: 1,
		ovaries: 1,
		intelligence: 85,
		energy: 55,
		attrXX: 40,
		attrXY: 80,
		fetish: "none",
		fetishKnown: 1,
		behavioralQuirk: "funny",
		sexualFlaw: "crude",
		counter: {birthsTotal: 16},
		bellySag: 5,
		skill: {vaginal: 35, oral: 15, servant: 15},
		geneticQuirks: {hyperFertility: 2},
		career: "a barista",
	},
];
