

/**
 * This holds all the female hero slaves that have incestious relations with other hero slaves.
 * See instructions in `slaveDatabase_000-instructions.md` for how to add to these databases.
 * Valid IDs start at 902001 and end at 904000.
 * @type {FC.HeroSlaveTemplate[]}
 */
App.Data.HeroSlaves.XXIncest = [
	{
		/* Added detail to origin. Added explicit birth surname to prevent different name from Kennerly. Added ovaries and set preg to "sterile". -DerangedLoner */
		ID: 902001,
		slaveName: "Camille",
		birthName: "Camille",
		birthSurname: "Andrews",
		origin: "$He is half of a famous musical duo, along with $his twin sister. They fled to the Free Cities after their incestuous relationship was uncovered by the media.",
		career: "an aspiring pop star",
		prestige: 1,
		prestigeDesc: "$He is a famed singer; citizens would pay top prices to feel $his mouth around their dicks.",
		birthWeek: 16,
		actualAge: 23,
		physicalAge: 23,
		visualAge: 23,
		ovaryAge: 23,
		health: {condition: 40},
		weight: -10,
		muscles: 10,
		height: 170,
		nationality: "American",
		race: "white",
		accent: 1,
		eye: {origColor: "blue"},
		origHColor: "blonde",
		origSkin: "pale",
		hLength: 60,
		hStyle: "bangs",
		waist: -55,
		voice: 2,
		boobs: 300,
		boobShape: "perky",
		butt: 2,
		preg: -2,
		ovaries: 1,
		face: 100,
		lips: 25,
		skill: {
			oral: 15,
			entertainment: 100
		},
		energy: 50,
		attrXX: 80,
		fetish: "boobs",
		fetishStrength: 70,
		behavioralFlaw: "arrogant",
		piercing: {ear: {weight: 1}},
		custom: {desc: "$He has an identical twin sister named Kennerly, from whom $he hates to be parted. They're from the former United States."},
		mother: -9999,
		father: -9998
	},
	{
		/* Added detail to origin. Added explicit birth surname to prevent different name from Kennerly. Added ovaries and set preg to "sterile". -DerangedLoner */
		ID: 902002,
		slaveName: "Kennerly",
		birthName: "Kennerly",
		birthSurname: "Andrews",
		origin: "$He is half of a famous musical duo, along with $his twin sister. They fled to the Free Cities after their incestuous relationship was uncovered by the media.",
		career: "an aspiring pop star",
		prestige: 1,
		prestigeDesc: "$He is a famed singer; citizens would pay top prices to feel $his mouth around their dicks.",
		birthWeek: 16,
		actualAge: 23,
		physicalAge: 23,
		visualAge: 23,
		ovaryAge: 23,
		health: {condition: 40},
		weight: 10,
		height: 167,
		nationality: "American",
		race: "white",
		accent: 1,
		markings: "beauty mark",
		eye: {origColor: "blue"},
		origHColor: "blonde",
		origSkin: "pale",
		hLength: 60,
		hStyle: "bangs",
		waist: -55,
		voice: 2,
		boobs: 500,
		boobShape: "perky",
		butt: 2,
		preg: -2,
		ovaries: 1,
		face: 100,
		lips: 15,
		skill: {
			oral: 15,
			entertainment: 100
		},
		energy: 50,
		attrXX: 80,
		fetish: "boobs",
		fetishStrength: 70,
		behavioralFlaw: "arrogant",
		piercing: {ear: {weight: 1}, navel: {weight: 1}},
		custom: {desc: "$He has an identical twin sister named Camille, from whom $he hates to be parted. They're from the former United States."},
		mother: -9999,
		father: -9998
	},
	{
		/* Careers benefiting from age prevent her and Qiang from being lolified in pedo mode. -DerangedLoner */
		ID: 902003,
		slaveName: "Bai",
		birthName: "Bai",
		origin: "As a teenager, she carried on a highly inappropriate relationship with her brother Qiang. While sex between teenaged siblings is taboo, sex between a married woman and the younger brother living with her family tends to end badly when her husband finds out.",
		actualAge: 38,
		visualAge: 38,
		physicalAge: 38,
		ovaryAge: 38,
		health: {condition: 60},
		devotion: 55,
		trust: 30,
		muscles: 0,
		height: 159,
		nationality: "Chinese",
		race: "asian",
		accent: 1,
		eye: {origColor: "brown"},
		origHColor: "jet black",
		pubicHColor: "jet black",
		underArmHStyle: "shaved",
		origSkin: "fair",
		hLength: 30,
		hStyle: "neat",
		waist: -30,
		boobs: 500,
		natural: {boobs: 500},
		hips: 0,
		butt: 2,
		preg: -1,
		ovaries: 1,
		face: 50,
		vagina: 2,
		vaginaLube: 1,
		anus: 1,
		energy: 65,
		intelligence: 65,
		intelligenceImplant: 30,
		attrXX: 40,
		attrXY: 80,
		skill: {
			oral: 15,
			vaginal: 35,
			entertainment: 15
		},
		fetish: "humiliation",
		fetishStrength: 30,
		fetishKnown: 1,
		behavioralFlaw: "hates women",
		sexualFlaw: "hates anal",
		career: "a teacher",
		mother: -9993,
		father: -9992,
		counter: {birthsTotal: 2},
	},
];
