
/**
 * This holds all the female hero slaves that have extreme problems.
 * This usually means they are missing all their limbs.
 * See instructions in `slaveDatabase_000-instructions.md` for how to add to these databases.
 * Valid IDs start at 908001 and end at 910000.
 * @type {FC.HeroSlaveTemplate[]}
 */
App.Data.HeroSlaves.XXExtreme = [
	{
		/* Increased nipples and areolae, changed eye color, added mute -BoneyM*/
		/* Removed birthName identical to slaveName--this would only make sense if she'd been born a slave to an owner who planned from her birth to amputate all her limbs, which is possible but unlikely. -DerangedLoner */
		ID: 908001,
		slaveName: "Mouse",
		actualAge: 21,
		physicalAge: 21,
		visualAge: 21,
		ovaryAge: 21,
		health: {condition: 20},
		devotion: -50,
		weight: 20,
		height: 152,
		race: "white",
		overrideHColor: 1,
		pubicHColor: "purple",
		origSkin: "pale",
		eye: {origColor: "blue"},
		origHColor: "purple",
		hLength: 10,
		boobs: 1000,
		areolae: 1,
		butt: 5,
		lipsTat: "permanent makeup",
		vagina: 1,
		vaginaLube: 1,
		anus: 1,
		analArea: 1,
		ovaries: 1,
		attrXY: 40,
		fetishKnown: 1,
		voice: 0,
		nipples: "puffy",
		_limbs: [0, 0, 0, 0]
	},
	{
		/* put some of $his custom description in $his origin (box stuff), tagged as amp, lowered obedience, increased weight but lowered health, changed skin color from white to pale */
		/* Made height explicit. Removed birthName identical to slaveName--this would only make sense if she'd been born a slave to an owner who planned from her birth to amputate all her limbs, which is possible but unlikely. -DerangedLoner */
		ID: 908002,
		slaveName: "Box",
		origin: "When you took $him from $his previous owner, $he was locked into a beautiful rosewood box lined with red velvet, crying.",
		actualAge: 21,
		physicalAge: 21,
		visualAge: 21,
		ovaryAge: 21,
		devotion: -75,
		weight: 20,
		height: 170,
		race: "white",
		overrideBrowHColor: 1,
		overrideArmHColor: 1,
		overridePubicHColor: 1,
		eyebrowHColor: "blonde",
		pubicHColor: "blonde",
		underArmHColor: "blonde",
		origSkin: "pale",
		origHColor: "golden blonde",
		hLength: 60,
		hStyle: "neat",
		boobs: 400,
		butt: 2,
		vagina: 1,
		vaginaLube: 1,
		anus: 1,
		ovaries: 1,
		skill: {
			vaginal: 15,
			oral: 15,
			anal: 15
		},
		intelligence: -50,
		attrXY: 40,
		fetishKnown: 1,
		custom: {desc: "$His amputation sites have titanium rings that go through to the bone. $He has been chemically blinded."},
		_limbs: [0, 0, 0, 0],
		eye: {
			left: {
				vision: 0
			},
			right: {
				vision: 0
			}
		}
	},
	{
		/* not much to change, lowered weight ('perfect slim body'), set to mute and changed flaw to odd- described as creepy */
		ID: 908003,
		slaveName: "Yukiko",
		birthName: "Yukiko",
		actualAge: 19,
		physicalAge: 19,
		visualAge: 19,
		ovaryAge: 19,
		health: {condition: 20},
		devotion: 100,
		weight: -20,
		race: "asian",
		nationality: "Japanese",
		origHColor: "black",
		pubicHColor: "black",
		origSkin: "very fair",
		hLength: 60,
		hStyle: "hime",
		boobs: 500,
		butt: 3,
		vaginaLube: 1,
		ovaries: 1,
		clothes: "a slave gown",
		intelligence: -40,
		intelligenceImplant: 30,
		attrXY: 40,
		fetishKnown: 1,
		behavioralFlaw: "odd",
		custom: {desc: "$He is a work of art: stoic, mysterious, doll-like — and always smiling."},
		voice: 0,
		_limbs: [0, 0, 0, 0],
	},
	{
		/* Added career to match origin. -DerangedLoner */
		ID: 908004,
		slaveName: "'Fucknugget' Pillow",
		birthName: "Anika",
		origin: "$He sold $himself into slavery to escape life on the streets.",
		actualAge: 37,
		physicalAge: 37,
		visualAge: 37,
		ovaryAge: 37,
		health: {condition: 80},
		devotion: 100,
		weight: 40,
		origRace: "white",
		overrideRace: 1,
		race: "latina",
		eye: {origColor: "blue"},
		origHColor: "red",
		pubicHColor: "red",
		hLength: 60,
		hStyle: "neat",
		waist: -100,
		boobs: 6260,
		natural: {boobs: 800},
		boobsImplant: 4200,
		boobsImplantType: "string",
		areolae: 3,
		boobsTat: "flowers",
		lactation: 2,
		lactationDuration: 2,
		butt: 12,
		buttImplant: 1,
		buttImplantType: "normal",
		buttTat: "flowers",
		face: 55,
		faceImplant: 15,
		lips: 55,
		lipsImplant: 10,
		lipsTat: "flowers",
		vagina: 3,
		vaginaLube: 1,
		vaginaTat: "flowers",
		preg: 37,
		pregType: 1,
		pregWeek: 37,
		pregKnown: 1,
		belly: 13000,
		bellyPreg: 13000,
		counter: {
			births: 2,
			birthsTotal: 2
		},
		anus: 2,
		ovaries: 1,
		anusTat: "flowers",
		makeup: 3,
		shouldersTat: "advertisements",
		stampTat: "flowers",
		skill: {
			vaginal: 100,
			oral: 100,
			anal: 100,
			whoring: 15
		},
		aphrodisiacs: 1,
		addict: 99,
		clothes: "restrictive latex",
		collar: "leather with cowbell",
		intelligence: -70,
		intelligenceImplant: 30,
		attrXY: 40,
		fetish: "boobs",
		fetishKnown: 1,
		piercing: {
			nipple: {weight: 2}, lips: {weight: 2}, tongue: {weight: 2}, vagina: {weight: 2}, anus: {weight: 2}, ear: {weight: 2}, nose: {weight: 2}, eyebrow: {weight: 2}, navel: {weight: 2}, genitals: {weight: 2, smart: true}
		},
		clitSetting: "boobs",
		_limbs: [0, 0, 0, 0],
		career: "homeless"
	},
	{
		/* Added ovaries and set preg to "sterile". -DerangedLoner */
		/* Added career to match origin. -DerangedLoner */
		ID: 908005,
		slaveName: "'Onahole' Lian the Liberty Whore",
		birthName: "Lian",
		origin: "$He is an enslaved member of an anti-slavery extremist group.",
		actualAge: 27,
		physicalAge: 27,
		visualAge: 27,
		ovaryAge: 27,
		health: {
			condition: -50,
			shortDamage: 10,
			longDamage: 10
		},
		devotion: 100,
		muscles: 20,
		nationality: "Chinese",
		race: "asian",
		origHColor: "black",
		pubicHColor: "black",
		origSkin: "pale",
		hLength: 0,
		hStyle: "shaved",
		waist: -100,
		boobs: 2000,
		natural: {boobs: 450},
		boobsImplant: 600,
		boobsImplantType: "normal",
		areolae: 2,
		butt: 8,
		face: 55,
		faceImplant: 65,
		vagina: 3,
		vaginaLube: 1,
		clit: 2,
		anus: 2,
		preg: -2,
		ovaries: 1,
		skill: {
			vaginal: 100,
			oral: 100,
			anal: 100,
			whoring: 100
		},
		collar: "shock punishment",
		shoes: "flats",
		intelligence: 25,
		intelligenceImplant: 30,
		energy: 100,
		attrXY: 40,
		fetishKnown: 1,
		_limbs: [0, 0, 0, 0],
		career: "a political activist"
	},
	{
		ID: 908006,
		slaveName: "'Quiet' Fay",
		birthName: "",
		birthSurname: "",
		origin: "As $he's always been a mute with no desire to communicate $his origin, you aren't sure where $he's from or how $he ended up here.",
		actualAge: 21,
		physicalAge: 21,
		visualAge: 21,
		ovaryAge: 21,
		health: {condition: -20},
		devotion: -100,
		height: 145,
		race: "white",
		origHColor: "brown",
		pubicHColor: "brown",
		origSkin: "white",
		hLength: 60,
		// @ts-expect-error custom hair style
		hStyle: "disheveled",
		boobs: 400,
		butt: 2,
		vaginaLube: 1,
		ovaries: 1,
		skill: {
			oral: 15
		},
		clothes: "a nice maid outfit",
		attrXY: 40,
		fetish: "submissive",
		custom: {
			tattoo: 'There\'s an "X" imprinted on $his throat where $his larynx would be.',
			desc: "$He earned $his name from $his permanent silence and fae physique."
		},
		voice: 0
	},
	{
		/* bitchy arrogant*/
		/* Added 'bitchy' quirk, reduced height and weight, added customDesc -BoneyM*/
		/* Made age explicit. -DerangedLoner */
		ID: 908007,
		slaveName: "Flora",
		birthName: "Flora",
		actualAge: 18,
		physicalAge: 18,
		visualAge: 18,
		ovaryAge: 18,
		health: {condition: 20},
		devotion: 25,
		weight: -20,
		height: 155,
		race: "white",
		origHColor: "blonde",
		pubicHColor: "blonde",
		origSkin: "white",
		hLength: 60,
		hStyle: "neat",
		boobs: 300,
		butt: 1,
		vagina: 1,
		vaginaLube: 1,
		anus: 1,
		ovaries: 1,
		skill: {
			vaginal: 35,
			oral: 100,
			anal: 35
		},
		energy: 100,
		attrXY: 40,
		fetishKnown: 1,
		behavioralFlaw: "bitchy",
		custom: {desc: "$He fits perfectly into a pillowcase."},
		_limbs: [0, 0, 0, 0],
	},
	{
		/* mindbroken*/
		/* Tweaked smart piercing setting, corrected piercings -BoneyM*/
		/* Set "birthName" to unknown, and added unknown "birthSurname". Added ovaries and set preg to "sterile". -DerangedLoner */
		ID: 908008,
		slaveName: "Cunt",
		birthName: "",
		birthSurname: "",
		actualAge: 19,
		physicalAge: 19,
		visualAge: 19,
		ovaryAge: 19,
		health: {condition: -10},
		devotion: 10,
		race: "white",
		origHColor: "blonde",
		pubicHColor: "blonde",
		origSkin: "white",
		hLength: 30,
		hStyle: "neat",
		heels: 1,
		boobs: 800,
		natural: {boobs: 350},
		boobsImplant: 600,
		boobsImplantType: "normal",
		butt: 4,
		buttImplant: 2,
		buttImplantType: "normal",
		vagina: 2,
		vaginaLube: 1,
		anus: 2,
		anusTat: "tribal patterns",
		preg: -2,
		ovaries: 1,
		skill: {
			vaginal: 15,
			oral: 15,
			anal: 35
		},
		intelligence: -70,
		attrXY: 40,
		attrKnown: 0,
		fetish: "mindbroken",
		fetishKnown: 1,
		piercing: {vagina: {weight: 2}, nose: {weight: 1}, genitals: {weight: 1}}
	},
	{
		/* heels*/
		/* Added origin, makeup and nails, changed eyes -BoneyM*/
		/* Set "birthName" to unknown, and added unknown "birthSurname". -DerangedLoner */
		ID: 908009,
		slaveName: "Fleshlight",
		birthName: "",
		birthSurname: "",
		origin: "Nothing remains of the person $he originally was, either mentally or physically.",
		actualAge: 21,
		physicalAge: 21,
		visualAge: 21,
		ovaryAge: 21,
		health: {condition: 20},
		devotion: 60,
		race: "white",
		eye: {origColor: "blue"},
		origHColor: "blonde",
		pubicHColor: "blonde",
		overrideSkin: 1,
		origSkin: "spray tanned",
		hLength: 60,
		hStyle: "neat",
		waist: -55,
		boobs: 800,
		natural: {boobs: 300},
		boobsImplant: 600,
		boobsImplantType: "normal",
		butt: 5,
		buttImplant: 2,
		buttImplantType: "normal",
		lips: 55,
		lipsImplant: 2,
		lipsTat: "permanent makeup",
		vagina: 2,
		vaginaLube: 1,
		anus: 2,
		ovaries: 1,
		makeup: 3,
		nails: 3,
		skill: {
			vaginal: 35,
			oral: 35,
			anal: 35
		},
		shoes: "heels",
		attrXY: 40,
		fetish: "mindbroken",
		fetishKnown: 1,
		custom: {desc: "$He has many surgical scars and something seems off about $him."},
		scar: {
			"left breast": {
				burn: 0,
				chain: 0,
				cutting: 0,
				exotic: 0,
				generic: 0,
				menacing: 0,
				surgical: 2,
				whip: 0
			},
			"right breast": {
				burn: 0,
				chain: 0,
				cutting: 0,
				exotic: 0,
				generic: 0,
				menacing: 0,
				surgical: 2,
				whip: 0
			},
		},
		leg: {
			left: {
				scar: {
					"left buttock": {
						burn: 0,
						chain: 0,
						cutting: 0,
						exotic: 0,
						generic: 0,
						menacing: 0,
						surgical: 2,
						whip: 0
					},
				},
			}, right: {
				scar: {
					"right buttock": {
						burn: 0,
						chain: 0,
						cutting: 0,
						exotic: 0,
						generic: 0,
						menacing: 0,
						surgical: 2,
						whip: 0
					},
				},
			}
		},
	},
	{
		/* Fixed customDesc syntax, changed hair from blue -BoneyM*/
		/* Set "birthName" to unknown, and added unknown "birthSurname". -DerangedLoner */
		ID: 908010,
		slaveName: "Whore",
		birthName: "",
		birthSurname: "",
		actualAge: 19,
		physicalAge: 19,
		visualAge: 19,
		ovaryAge: 19,
		health: {condition: 20},
		devotion: 100,
		height: 155,
		race: "white",
		origSkin: "white",
		hLength: 60,
		hStyle: "braided",
		boobs: 400,
		butt: 2,
		vagina: 1,
		vaginaLube: 1,
		anus: 1,
		ovaries: 1,
		skill: {
			vaginal: 15,
			oral: 15,
			anal: 15
		},
		attrXY: 40,
		fetish: "mindbroken",
		fetishKnown: 1,
		custom: {
			desc: "$He is a complete mental blank; to $him, there is only the Master."
		},
	},
];
