/**
 * @file this file defines both App.Data.HeroSlaves.XXFruitGirls and App.Data.HeroSlave.XXFruitGirlsExtreme.
 * @see App.Data.HeroSlaves.XXFruitGirls
 * @see App.Data.HeroSlaves.XXFruitGirlsExtreme
 */

/**
 * This defines the normal fruit girls.
 * It is one of the few slave databases that should be kept as close to their original implementations as possible.
 * Valid IDs start at 906001 and end at 907000.
 * @type {FC.HeroSlaveTemplate[]}
 */
App.Data.HeroSlaves.XXFruitGirls = [
	{
		ID: 906001,
		slaveName: "Cherry",
		birthName: "Cherry",
		slaveSurname: "",
		birthSurname: "",
		health: {condition: 20},
		devotion: 75,
		race: "white",
		actualAge: 18,
		physicalAge: 18,
		visualAge: 18,
		ovaryAge: 18,
		nationality: "stateless",
		eye: {origColor: "light brown"},
		pubicHColor: "black",
		origSkin: "white",
		origHColor: "black",
		hStyle: "neat",
		hLength: 60,
		pubicHStyle: "waxed",
		boobs: 500,
		butt: 3,
		lips: 35,
		vagina: 1,
		vaginaLube: 1,
		preg: -2,
		ovaries: 1,
		skill: {vaginal: 35},
		attrXY: 40,
		fetish: "submissive",
		fetishKnown: 1,
		lipsTat: "Two cherries are tattooed on $his left cheek.",
		buttTat: "Two cherries are tattooed on $his right butt cheek.",
		piercing: {nipple: {weight: 1}, vagina: {weight: 2}, genitals: {weight: 2}},
		counter: {birthsTotal: 1}
	},
	/* vag implant, vibe nips*/
	/* Added blank birth surname and stateless nationality to prevent ones from being randomly generated. Added blank slave
		surname to prevent birth surname from being described as unknown. -DerangedLoner */
	{
		ID: 906002,
		slaveName: "Strawberry",
		birthName: "Strawberry",
		slaveSurname: "",
		birthSurname: "",
		actualAge: 30,
		physicalAge: 30,
		visualAge: 30,
		ovaryAge: 30,
		health: {condition: 20},
		devotion: 40,
		nationality: "stateless",
		race: "white",
		height: 175,
		eye: {origColor: "dark brown"},
		origHColor: "blonde",
		pubicHColor: "blonde",
		overrideSkin: 1,
		origSkin: "sun tanned",
		hStyle: "neat",
		hLength: 60,
		pubicHStyle: "waxed",
		waist: -55,
		boobs: 1000,
		natural: {boobs: 600},
		boobsImplant: 400,
		boobsImplantType: "normal",
		butt: 5,
		buttImplant: 2,
		buttImplantType: "normal",
		lips: 35,
		lipsImplant: 10,
		vagina: 2,
		vaginaLube: 1,
		preg: -2,
		anus: 2,
		ovaries: 1,
		skill: {vaginal: 35, oral: 35, anal: 35},
		attrXY: 40,
		fetish: "humiliation",
		fetishKnown: 1,
		lipsTat: "Strawberries are tattooed on $his left cheek.",
		buttTat: "Strawberries are tattooed on $his right buttock.",
		piercing: {nipple: {weight: 1}, vagina: {weight: 2}, genitals: {weight: 2}},
		counter: {birthsTotal: 2}
	},
	/* vibe nips, muscles*/
	/* Added blank birth surname and stateless nationality to prevent ones from being randomly generated. Added blank slave
		surname to prevent birth surname from being described as unknown. -DerangedLoner */
	{
		ID: 906003,
		slaveName: "Melon",
		birthName: "Melon",
		slaveSurname: "",
		birthSurname: "",
		actualAge: 23,
		physicalAge: 23,
		visualAge: 23,
		ovaryAge: 23,
		health: {condition: 20},
		devotion: 50,
		height: 175,
		nationality: "stateless",
		race: "white",
		eye: {origColor: "blue"},
		origHColor: "red",
		pubicHColor: "red",
		overrideSkin: 1,
		origSkin: "sun tanned",
		hLength: 10,
		hStyle: "neat",
		pubicHStyle: "waxed",
		boobs: 1800,
		natural: {boobs: 1000},
		boobsImplant: 800,
		boobsImplantType: "fillable",
		butt: 4,
		lips: 35,
		lipsImplant: 10,
		vagina: 2,
		vaginaLube: 1,
		preg: -2,
		anus: 2,
		ovaries: 1,
		skill: {vaginal: 15, oral: 100, anal: 15},
		attrXY: 40,
		fetish: "submissive",
		fetishKnown: 1,
		lipsTat: "Watermelons are tattooed on $his face.",
		buttTat: "Watermelons are tattooed on $his buttocks.",
		teeth: "removable",
		piercing: {
			nipple: {weight: 1}, vagina: {weight: 2}, genitals: {weight: 2}, lips: {weight: 2}
		},
		counter: {birthsTotal: 1}
	},
	/* vibe nips, saliva implant*/
	/* Added blank birth surname and stateless nationality to prevent ones from being randomly generated. Added blank slave
		surname to prevent birth surname from being described as unknown. -DerangedLoner */
	{
		ID: 906004,
		slaveName: "Carambola",
		birthName: "Carambola",
		slaveSurname: "",
		birthSurname: "",
		actualAge: 25,
		physicalAge: 25,
		visualAge: 25,
		ovaryAge: 25,
		health: {condition: 20},
		devotion: 90,
		nationality: "stateless",
		race: "white",
		height: 175,
		eye: {origColor: "light green"},
		origHColor: "dark blonde",
		pubicHColor: "dark blonde",
		overrideSkin: 1,
		origSkin: "sun tanned",
		hLength: 60,
		// @ts-expect-error custom hair style
		hStyle: "in curly pigtails",
		pubicHStyle: "waxed",
		boobs: 650,
		butt: 8,
		buttImplant: 4,
		buttImplantType: "fillable",
		lips: 35,
		vagina: 1,
		vaginaLube: 1,
		preg: -2,
		anus: 3,
		ovaries: 1,
		skill: {vaginal: 15, oral: 15, anal: 100},
		attrXY: 40,
		fetish: "buttslut",
		fetishKnown: 1,
		lipsTat: "Carambolas — starfruits — are tattooed on $his face.",
		buttTat: "Carambolas — starfruits — are tattooed on $his buttocks.",
		piercing: {
			nipple: {weight: 1}, vagina: {weight: 2}, genitals: {weight: 2}, tongue: {weight: 1}
		},
		clothes: "no clothing",
		collar: "bell collar",
		heels: 1
	},
	/* vibe nips, saliva implant lube*/
	/* Added blank birth surname and stateless nationality to prevent ones from being randomly generated. Added blank slave
		surname to prevent birth surname from being described as unknown. -DerangedLoner */
	{
		ID: 906005,
		slaveName: "Banana",
		actualAge: 28,
		physicalAge: 28,
		visualAge: 28,
		ovaryAge: 28,
		health: {condition: 20},
		devotion: 65,
		race: "latina",
		origHColor: "black",
		pubicHColor: "black",
		origSkin: "brown",
		boobs: 400,
		butt: 5,
		lips: 35,
		vagina: 2,
		vaginaLube: 1,
		preg: -2,
		anus: 2,
		ovaries: 1,
		skill: {
			vaginal: 35, oral: 100, anal: 35, penetrative: 15
		},
		attrXY: 40,
		fetish: "submissive",
		fetishKnown: 1,
		lipsTat: "Bananas are tattooed on $his face.",
		buttTat: "Bananas are tattooed on $his buttocks.",
		teeth: "removable",
		piercing: {nipple: {weight: 1}, vagina: {weight: 2}, genitals: {weight: 2}},
		hips: 1,
		labia: 2,
		clit: 1,
		bald: 1,
		hLength: 0,
		hStyle: "bald",
		pubicHStyle: "bald",
		underArmHStyle: "bald",
		intelligence: -30
	},
	/* vibe nips, big pusslips+clit*/
	{
		ID: 906006,
		slaveName: "Green Grape",
		birthName: "Green Grape",
		slaveSurname: "",
		birthSurname: "",
		health: {condition: 20},
		devotion: 40,
		actualAge: 18,
		physicalAge: 18,
		visualAge: 18,
		ovaryAge: 18,
		birthWeek: 27,
		nationality: "stateless",
		race: "mixed race",
		eye: {origColor: "green"},
		origHColor: "black",
		pubicHColor: "black",
		origSkin: "pale",
		hLength: 60,
		hStyle: "neat",
		pubicHStyle: "waxed",
		boobs: 650,
		butt: 4,
		vagina: 1,
		vaginaLube: 1,
		preg: -2,
		anus: 1,
		ovaries: 1,
		skill: {vaginal: 35, oral: 35, anal: 35},
		attrXX: 80,
		attrXY: 40,
		fetishKnown: 1,
		lipsTat: "Green grapes are tattooed on $his face.",
		buttTat: "Green grapes are tattooed on $his buttocks.",
		mother: -9995,
		father: -9994,
		piercing: {nipple: {weight: 1}, vagina: {weight: 2}, genitals: {weight: 2}},
		intelligence: -60,
		custom: {desc: "Aside from the age difference, $he and $his older sister Purple Grape are two peas in a pod...well, two grapes in a bunch."},
	},
	/* vibe nips, implant link to sister*/
	/* Added blank birth surname and stateless nationality to prevent ones from being randomly generated. Added blank slave
		surname to prevent birth surname from being described as unknown. Added custom desc referencing sister.-DerangedLoner */
	{
		ID: 906007,
		slaveName: "Purple Grape",
		birthName: "Purple Grape",
		slaveSurname: "",
		birthSurname: "",
		actualAge: 23,
		physicalAge: 23,
		visualAge: 23,
		ovaryAge: 23,
		birthWeek: 6,
		health: {condition: 20},
		devotion: 40,
		nationality: "stateless",
		race: "mixed race",
		eye: {origColor: "black"},
		origHColor: "black",
		pubicHColor: "black",
		origSkin: "brown",
		hLength: 60,
		hStyle: "neat",
		pubicHStyle: "waxed",
		boobs: 650,
		butt: 4,
		vagina: 1,
		vaginaLube: 1,
		preg: -2,
		anus: 1,
		ovaries: 1,
		skill: {vaginal: 35, oral: 35, anal: 35},
		attrXX: 80,
		attrXY: 40,
		fetishKnown: 1,
		lipsTat: "Purple grapes are tattooed on $his face.",
		buttTat: "Purple grapes are tattooed on $his buttocks.",
		mother: -9995,
		father: -9994,
		piercing: {nipple: {weight: 1}, vagina: {weight: 2}, genitals: {weight: 2}},
		intelligence: -60,
		custom: {desc: "Aside from the age difference, $he and $his younger sister Green Grape are two peas in a pod...well, two grapes in a bunch."},
	},
	/* vibe nips, implant link to sister */
	/* Added blank birth surname and stateless nationality to prevent ones from being randomly generated. Added blank slave
		surname to prevent birth surname from being described as unknown. Added custom desc referencing sister. -DerangedLoner */
	{
		ID: 906008,
		slaveName: "Apple",
		birthName: "Apple",
		slaveSurname: "",
		birthSurname: "",
		actualAge: 28,
		physicalAge: 28,
		visualAge: 28,
		ovaryAge: 28,
		health: {condition: 20},
		devotion: 75,
		muscles: 20,
		nationality: "stateless",
		race: "white",
		eye: {origColor: "dark brown"},
		pubicHColor: "black",
		origSkin: "pale",
		origHColor: "black",
		hLength: 60,
		hStyle: "neat",
		pubicHStyle: "waxed",
		boobs: 500,
		butt: 3,
		lips: 55,
		lipsTat: "permanent makeup",
		vagina: 3,
		vaginaLube: 1,
		preg: -2,
		ovaries: 1,
		skill: {vaginal: 15, oral: 35},
		vaginalAccessory: "large dildo",
		buttplug: "large plug",
		attrXY: 40,
		fetish: "submissive",
		fetishKnown: 1,
		custom: {tattoo: "Cored apples are tattooed on $his face."},
		buttTat: "Cored apples are tattooed on $his buttocks.",
		intelligence: -60,
		piercing: {nipple: {weight: 1}, vagina: {weight: 2}, genitals: {weight: 2}},
	},
	/* vibe nips, stupid, sensitive, no masturbation implant*/
	/* Added blank birth surname and stateless nationality to prevent ones from being randomly generated. Added blank slave
		surname to prevent birth surname from being described as unknown. -DerangedLoner */
];

/**
 * This defines the extreme fruit girls.
 * It is one of the few slave databases that should be kept as close to their original implementations as possible.
 * Valid IDs start at 907001 and end at 908000.
 * @type {FC.HeroSlaveTemplate[]}
 */
App.Data.HeroSlaves.XXFruitGirlsExtreme = [
	{
		/* vibe nips, can act as furniture*/
		/* Added blank birth surname and stateless nationality to prevent ones from being randomly generated. Added blank slave
			surname to prevent birth surname from being described as unknown. -DerangedLoner */
		ID: 907001,
		slaveName: "Plum",
		birthName: "Plum",
		slaveSurname: "",
		birthSurname: "",
		actualAge: 28,
		physicalAge: 28,
		visualAge: 28,
		ovaryAge: 28,
		health: {condition: 20},
		devotion: 75,
		muscles: 30,
		weight: 20,
		nationality: "stateless",
		race: "white",
		eye: {origColor: "brown"},
		origHColor: "brown",
		origSkin: "pale",
		hLength: 10,
		// @ts-expect-error custom hair style
		hStyle: "wavy",
		pubicHStyle: "waxed",
		boobs: 400,
		butt: 2,
		lips: 35,
		vagina: 5,
		vaginaLube: 1,
		preg: -2,
		anus: 2,
		ovaries: 1,
		skill: {vaginal: 15, oral: 15, anal: 15},
		buttplug: "large plug",
		attrXY: 40,
		fetishKnown: 1,
		lipsTat: "Cored plums are tattooed on $his face.",
		buttTat: "Cored plums are tattooed on $his buttocks.",
		piercing: {
			nipple: {weight: 1}, vagina: {weight: 2}, genitals: {weight: 2}, corset: {weight: 1, desc: "$He has massive C-clamp piercings in $his back that allow $him to act as furniture"}
		},
		sexualFlaw: "self hating",
		clothes: "no clothing",
		vaginalAccessory: "long, huge dildo"
	},
];
