

/**
 * This holds all the male hero slaves that have extreme problems.
 * This usually means they are missing all their limbs.
 * See instructions in `slaveDatabase_000-instructions.md` for how to add to these databases.
 * Valid IDs start at 808001 and end at 910000.
 * @type {FC.HeroSlaveTemplate[]}
 */
App.Data.HeroSlaves.XYExtreme = [
	{
		/* Changed "preg" of -3 (meaningless without a vagina and ovaries, but seemingly intentional, since the others in this script mostly had -2)
			to "ballType" of "sterile". Deleted female birth name, then added male one to prevent possible random generation of a female one. -DerangedLoner */
		ID: 808001,
		slaveName: "'Udders' Erika",
		birthName: "Eric",
		genes: "XY",
		actualAge: 28,
		physicalAge: 28,
		visualAge: 28,
		ovaryAge: 28,
		health: {condition: 90},
		devotion: 55,
		height: 145,
		race: "white",
		eye: {origColor: "blue"},
		origSkin: "fair",
		hLength: 60,
		hStyle: "neat",
		pubicHStyle: "in a strip",
		boobs: 1250,
		natural: {boobs: 750},
		areolae: 2,
		boobsTat: "bovine patterns",
		lactation: 2,
		lactationDuration: 2,
		butt: 2,
		buttTat: "bovine patterns",
		lips: 55,
		lipsImplant: 10,
		lipsTat: "bovine patterns",
		vagina: -1,
		vaginaTat: "bovine patterns",
		ballType: "sterile",
		anus: 2,
		dick: 1,
		dickTat: "bovine patterns",
		prostate: 1,
		anusTat: "bovine patterns",
		shouldersTat: "bovine patterns",
		armsTat: "bovine patterns",
		legsTat: "bovine patterns",
		stampTat: "bovine patterns",
		skill: {oral: 100, anal: 100, entertainment: 35},
		collar: "leather with cowbell",
		attrXX: 40,
		attrXY: 40,
		fetish: "boobs",
		fetishKnown: 1,
		voice: 0,
		piercing: {nose: {weight: 2}, genitals: {weight: 2, smart: true}},
		clitSetting: "boobs",
		custom: {desc: "Though $his vocal cords have been altered to keep $him from speaking, $he is still capable of the occasional moo."}
	},
	{
		/* Deleted birth names identical to obviously made-up slave names, then added male one to prevent possible random generation of a female one.
			Removed limbs to match origin. Removed "preg" of 0, which is meaningless without vagina/ovaries or an anal womb, and is the default anyway. -DerangedLonger */
		ID: 808002,
		slaveName: "Danny 'The D'",
		birthName: "Daniel",
		slaveSurname: "Ildoe",
		genes: "XY",
		origin: "Born without limbs and abandoned by $his parents, $he was taken in by a posh family, given a massive cock, and trained to be the wealthy lady's perfect living sex toy.",
		actualAge: 28,
		visualAge: 28,
		physicalAge: 28,
		ovaryAge: 28,
		health: {condition: 100},
		devotion: 100,
		muscles: 50,
		height: 94,
		race: "white",
		eye: {origColor: "blue"},
		origHColor: "black",
		pubicHColor: "black",
		overrideSkin: 1,
		origSkin: "spray tanned",
		hLength: 10,
		hStyle: "neat",
		waist: 55,
		boobs: 50,
		natural: {boobs: 300},
		hips: -1,
		butt: 0,
		face: 45,
		vagina: -1,
		dick: 6,
		balls: 10,
		scrotum: 7,
		prostate: 2,
		anusTat: "bleached",
		energy: 95,
		intelligenceImplant: 30,
		attrXX: 100,
		attrXY: 0,
		skill: {oral: 95, penetrative: 95},
		fetish: "submissive",
		fetishKnown: 1,
		behavioralQuirk: "advocate",
		_limbs: [0, 0, 0, 0],
	},
];
