/**
 * THE WORLD PASSES — the week, the guards, the rules engine, and the generator.
 *
 * The week test is the important one here: an arcology sim that throws on week nine is worthless
 * however good its model of a person is, and the failure mode of a pipeline this size is a nullish
 * read three passes deep on a state nobody generated by hand.
 */
import { check } from "./harness.ts";
import { newGame } from "../src/engine/state.ts";
import { endWeek } from "../src/engine/week.ts";
import { generatePerson } from "../src/engine/generate.ts";
import { applyDiff, showsDeparture, findInteriorLeak, findMaxim, findEcho } from "../src/engine/turn.ts";
import { preview, runOrders, describe, assignToFacility } from "../src/engine/rules.ts";
import { scoreFor, axesOf, explainFor, adoptDoctrine } from "../src/engine/society.ts";
import { DOCTRINE_BY_ID } from "../src/data/doctrines.ts";
import { tryConception } from "../src/engine/pregnancy.ts";
import { newMemory } from "../src/engine/memory.ts";
import { refresh } from "../src/engine/obedience.ts";

/* ── the week survives being run ────────────────────────────────────────────────────────────── */
{
  const s = newGame({ seed: "test-week", starting_slaves: 5, difficulty: "standard" });
  // Put people to work, including in the two places that hurt.
  const ids = Object.keys(s.people);
  s.arcology.facilities["brothel"].level = 1;
  s.arcology.facilities["brothel"].capacity = 6;
  s.arcology.facilities["arcade"].level = 1;
  s.arcology.facilities["arcade"].capacity = 6;
  assignToFacility(s, s.people[ids[0]], "brothel");
  assignToFacility(s, s.people[ids[1]], "arcade");
  s.people[ids[2]].assignment = "whore";
  adoptDoctrine(s, "paternalist");

  let threw: unknown = null;
  let cashMatchedLedger = true;
  try {
    for (let i = 0; i < 26; i++) {
      const before = s.arcology.cash;
      const rep = endWeek(s);
      const ledgerSum = rep.ledger.reduce((n, l) => n + l.cash, 0);
      // Every cash movement is a ledger line; the totals are the sum of the lines and nothing else.
      if (Math.abs((before + ledgerSum) - rep.cash_end) > 1) cashMatchedLedger = false;
    }
  } catch (e) { threw = e; }

  check("twenty-six weeks run without throwing", !threw, threw);
  check("the ledger accounts for every movement of cash", cashMatchedLedger);
  check("the week advances the clock exactly once each time", s.arcology.week === 27, s.arcology.week);
  check("reports are kept", s.reports.length > 0);

  const arcadeWorker = s.people[ids[1]];
  check("a season in the arcade wears the resting point down", arcadeWorker.psyche.capacity < arcadeWorker.psyche.capacity_born, {
    born: arcadeWorker.psyche.capacity_born, now: arcadeWorker.psyche.capacity,
  });
  check("and it is remembered rather than only felt", (s.memory[ids[1]]?.episodic.length ?? 0) > 0);
}

/* ── the arcology can pay for itself ───────────────────────────────────────────────────────────
 * The first version of the economy billed the owner for feeding the entire citizen population at
 * import prices — twelve thousand a week against a rent roll of four hundred — so every save was
 * insolvent by week five and dead by week twelve, whatever the player did. Found by running a
 * year and reading the ledger, which is what tools/balance.ts is for.
 */
{
  const s = newGame({ seed: "test-solvency", starting_slaves: 3 });
  for (let i = 0; i < 12; i++) endWeek(s);
  check("an arcology left entirely alone is not insolvent in a season", s.arcology.cash > 0, s.arcology.cash);
  check("and its people are alive", Object.values(s.people).every((p) => p.status !== "dead"));
  const workers = Object.values(s.people).filter((p) => p.status === "owned");
  check("resting bodies recover rather than grinding down", workers.every((p) => p.health.energy > 40));
}

/* ── the departure guard ────────────────────────────────────────────────────────────────────── */
{
  const s = newGame({ seed: "test-guard", starting_slaves: 2 });
  const [a, b] = Object.keys(s.people);
  s.scene.present = [a, b];
  const prose = `${s.people[a].name} stays where she is, hands flat on the table. ${s.people[b].name} says nothing at all.`;

  const notes = applyDiff(s, { present_remove: [a, b] }, prose);
  check("the bookkeeper cannot empty a room the prose wrote as full", s.scene.present.length === 2, s.scene.present);
  check("and it says so, rather than failing silently", notes.length === 2, notes);

  const leaving = `${s.people[a].name} left without answering.`;
  applyDiff(s, { present_remove: [a] }, leaving);
  check("a departure the prose actually shows goes through", !s.scene.present.includes(a));

  check("name probes work on the first name alone", showsDeparture("Mara left without answering.", "Mara Volkova"));
  check("and do not fire on somebody merely mentioned", !showsDeparture("Mara was still sitting there when the others left the floor above.", "Mara"));
  check("nor when the departure is in a different sentence about somebody else", !showsDeparture("Mara put the cup down. The steward left.", "Mara"));
}

/* ── only witnesses learn ───────────────────────────────────────────────────────────────────── */
{
  const s = newGame({ seed: "test-witness", starting_slaves: 3 });
  const [a, , c] = Object.keys(s.people);
  s.scene.present = [a];
  applyDiff(s, { memories: [{ id: c, content: "heard the whole thing from the kitchen", importance: 7 }] }, "Nothing much happened.");
  check("a memory cannot be filed for somebody who was not in the room", (s.memory[c]?.episodic.length ?? 0) === 0);
  applyDiff(s, { memories: [{ id: a, content: "what was actually said", importance: 7 }] }, "Nothing much happened.");
  check("and it can for somebody who was", (s.memory[a]?.episodic.length ?? 0) === 1);
}

/* ── the detectors ──────────────────────────────────────────────────────────────────────────── */
{
  const s = newGame({ seed: "test-detect", starting_slaves: 1 });
  const name = s.people[Object.keys(s.people)[0]].name;
  check("an interior the narrator was not given is caught",
    !!findInteriorLeak(`${name} felt the whole thing settle into place.`, s));
  check("and its nicer coat is caught too",
    !!findInteriorLeak("Something tightened behind her eyes.", s));
  check("dialogue is not a violation",
    !findInteriorLeak(`"I knew you would say that," she said.`, s));
  check("a maxim is caught", !!findMaxim(`She shrugged. "People always want what they cannot have."`));
  check("an ordinary line is not", !findMaxim(`She shrugged. "I told you already, I am not doing it."`));
  check("the narrator handing your own line back is caught",
    !!findEcho("You tell her to get out of the room. She does not move.", "you tell her to get out of the room"));
}

/* ── the rules engine ───────────────────────────────────────────────────────────────────────── */
{
  const s = newGame({ seed: "test-rules", starting_slaves: 4 });
  for (const p of Object.values(s.people)) { p.health.health = -60; refresh(p, s.memory[p.id]); }
  const order = s.orders.find((o) => o.id === "o-health")!;

  const before = JSON.stringify(s.people);
  const shown = preview(s, order);
  check("the dry run finds who it would touch", shown.length === 4, shown.length);
  check("and changes absolutely nothing", JSON.stringify(s.people) === before);

  const ran = runOrders(s, false);
  check("running it for real does change them", ran.length > 0 && Object.values(s.people).every((p) => p.health.curatives === 1));
  check("and the person records which rule did it", Object.values(s.people).every((p) => p.rules_applied.includes("o-health")));
  check("a rule renders as a sentence", /^When .* — /.test(describe(order)), describe(order));
}

/* ── doctrine scoring ───────────────────────────────────────────────────────────────────────── */
{
  const s = newGame({ seed: "test-doctrine", starting_slaves: 1 });
  const p = Object.values(s.people)[0];
  p.body.boobs = 1600;
  p.body.butt = 8;
  const expansionist = scoreFor(p, DOCTRINE_BY_ID["expansionist"]);
  const slim = scoreFor(p, DOCTRINE_BY_ID["slimness"]);
  check("opposed doctrines read the same body in opposite directions", expansionist > 0.3 && slim < -0.3, { expansionist, slim });
  check("the axes are bounded", Object.values(axesOf(p)).every((v) => v >= -1 && v <= 1));

  adoptDoctrine(s, "expansionist");
  const clash = adoptDoctrine(s, "slimness");
  check("and they cannot be held at the same time", !clash.ok, clash);
  check("the arcology can explain its opinion of a person", explainFor(s, p).length > 0, explainFor(s, p));
}

/* ── the generator ──────────────────────────────────────────────────────────────────────────── */
{
  const a = generatePerson({ seed: "same" });
  const b = generatePerson({ seed: "same" });
  check("the same seed makes the same person", a.name === b.name && a.body.height_cm === b.body.height_cm && a.psyche.capacity_born === b.psyche.capacity_born);
  const c = generatePerson({ seed: "different" });
  check("a different seed does not", a.name !== c.name || a.body.height_cm !== c.body.height_cm);

  const many = Array.from({ length: 60 }, (_, i) => generatePerson({ seed: `spread:${i}` }));
  const styles = new Set(many.map((p) => p.persona.attachment.style));
  check("temperaments spread rather than clustering on one", styles.size >= 3, [...styles]);
  const capacities = many.map((p) => p.psyche.capacity_born);
  check("resting points vary", Math.max(...capacities) - Math.min(...capacities) > 3);
  check("everybody arrives with a body described in words", many.every((p) => p.body.appearance_facts.length > 20));
}

/* ── conception ─────────────────────────────────────────────────────────────────────────────── */
{
  const s = newGame({ seed: "test-preg", starting_slaves: 2 });
  const [a, b] = Object.values(s.people);
  a.womb.sterile = false;
  a.womb.fertility = 100;
  a.womb.cycle_day = 14;
  a.womb.contraceptives = true;
  let got = 0;
  for (let i = 0; i < 200; i++) if (tryConception(s, a, b.id, 6)) got++;
  check("contraceptives are absolute", got === 0);

  a.womb.contraceptives = false;
  a.womb.cycle_day = 2;
  let outside = 0;
  for (let i = 0; i < 300; i++) { if (tryConception(s, a, b.id, 6)) { outside++; a.womb.fetuses = []; } }
  a.womb.cycle_day = 14;
  let inside = 0;
  for (let i = 0; i < 300; i++) { if (tryConception(s, a, b.id, 6)) { inside++; a.womb.fetuses = []; } }
  check("the fertile window is a real window", inside > outside * 3, { inside, outside });
}

/* ── facility membership has one writer ─────────────────────────────────────────────────────── */
{
  const s = newGame({ seed: "test-facility", starting_slaves: 3 });
  s.arcology.facilities["spa"].level = 1;
  s.arcology.facilities["spa"].capacity = 1;
  const [a, b] = Object.values(s.people);
  assignToFacility(s, a, "spa");
  assignToFacility(s, b, "spa");
  check("a full facility refuses the next body", s.arcology.facilities["spa"].workers.length === 1);
  check("and the person is not left pointing at it", b.facility === undefined);
  assignToFacility(s, a, undefined);
  check("leaving a facility clears both sides", !s.arcology.facilities["spa"].workers.length && a.facility === undefined);
}
