/**
 * THE WORLD PASSES — the week, the guards, the rules engine, and the generator.
 *
 * The week test is the important one here: an arcology sim that throws on week nine is worthless
 * however good its model of a person is, and the failure mode of a pipeline this size is a nullish
 * read three passes deep on a state nobody generated by hand.
 */
import { check } from "./harness.ts";
import { newGame } from "../src/engine/state.ts";
import { endWeek } from "../src/engine/week.ts";
import { generatePerson } from "../src/engine/generate.ts";
import { applyDiff, showsDeparture, findInteriorLeak, findMaxim, findEcho } from "../src/engine/turn.ts";
import { preview, runOrders, describe, assignToFacility, isMinor, setAssignment, allowedAssignments } from "../src/engine/rules.ts";
import { scoreFor, axesOf, explainFor, adoptDoctrine } from "../src/engine/society.ts";
import { DOCTRINE_BY_ID } from "../src/data/doctrines.ts";
import { tryConception, tickAge } from "../src/engine/pregnancy.ts";
import { newMemory } from "../src/engine/memory.ts";
import { refresh } from "../src/engine/obedience.ts";
import { runManager } from "../src/engine/managers.ts";
import { enact, tickPolicies } from "../src/engine/policies.ts";
import { Ledger } from "../src/engine/economy.ts";
import { unrest } from "../src/engine/security.ts";
import { EVENTS, pressure } from "../src/engine/events.ts";
import { practise, skill } from "../src/engine/player.ts";

/* ── the week survives being run ────────────────────────────────────────────────────────────── */
{
  const s = newGame({ seed: "test-week", starting_slaves: 5, difficulty: "standard" });
  // Put people to work, including in the two places that hurt.
  const ids = Object.keys(s.people);
  s.arcology.facilities["brothel"].level = 1;
  s.arcology.facilities["brothel"].capacity = 6;
  s.arcology.facilities["arcade"].level = 1;
  s.arcology.facilities["arcade"].capacity = 6;
  assignToFacility(s, s.people[ids[0]], "brothel");
  assignToFacility(s, s.people[ids[1]], "arcade");
  s.people[ids[2]].assignment = "whore";
  adoptDoctrine(s, "paternalist");

  let threw: unknown = null;
  let cashMatchedLedger = true;
  try {
    for (let i = 0; i < 26; i++) {
      const before = s.arcology.cash;
      const rep = endWeek(s);
      const ledgerSum = rep.ledger.reduce((n, l) => n + l.cash, 0);
      // Every cash movement is a ledger line; the totals are the sum of the lines and nothing else.
      if (Math.abs((before + ledgerSum) - rep.cash_end) > 1) cashMatchedLedger = false;
    }
  } catch (e) { threw = e; }

  check("twenty-six weeks run without throwing", !threw, threw);
  check("the ledger accounts for every movement of cash", cashMatchedLedger);
  check("the week advances the clock exactly once each time", s.arcology.week === 27, s.arcology.week);
  check("reports are kept", s.reports.length > 0);

  const arcadeWorker = s.people[ids[1]];
  check("a season in the arcade wears the resting point down", arcadeWorker.psyche.capacity < arcadeWorker.psyche.capacity_born, {
    born: arcadeWorker.psyche.capacity_born, now: arcadeWorker.psyche.capacity,
  });
  check("and it is remembered rather than only felt", (s.memory[ids[1]]?.episodic.length ?? 0) > 0);
}

/* ── the arcology can pay for itself ───────────────────────────────────────────────────────────
 * The first version of the economy billed the owner for feeding the entire citizen population at
 * import prices — twelve thousand a week against a rent roll of four hundred — so every save was
 * insolvent by week five and dead by week twelve, whatever the player did. Found by running a
 * year and reading the ledger, which is what tools/balance.ts is for.
 */
{
  const s = newGame({ seed: "test-solvency", starting_slaves: 3 });
  for (let i = 0; i < 12; i++) endWeek(s);
  check("an arcology left entirely alone is not insolvent in a season", s.arcology.cash > 0, s.arcology.cash);
  check("and its people are alive", Object.values(s.people).every((p) => p.status !== "dead"));
  const workers = Object.values(s.people).filter((p) => p.status === "owned");
  check("resting bodies recover rather than grinding down", workers.every((p) => p.health.energy > 40));
}

/* ── the departure guard ────────────────────────────────────────────────────────────────────── */
{
  const s = newGame({ seed: "test-guard", starting_slaves: 2 });
  const [a, b] = Object.keys(s.people);
  s.scene.present = [a, b];
  const prose = `${s.people[a].name} stays where she is, hands flat on the table. ${s.people[b].name} says nothing at all.`;

  const notes = applyDiff(s, { present_remove: [a, b] }, prose);
  check("the bookkeeper cannot empty a room the prose wrote as full", s.scene.present.length === 2, s.scene.present);
  check("and it says so, rather than failing silently", notes.length === 2, notes);

  const leaving = `${s.people[a].name} left without answering.`;
  applyDiff(s, { present_remove: [a] }, leaving);
  check("a departure the prose actually shows goes through", !s.scene.present.includes(a));

  check("name probes work on the first name alone", showsDeparture("Mara left without answering.", "Mara Volkova"));
  check("and do not fire on somebody merely mentioned", !showsDeparture("Mara was still sitting there when the others left the floor above.", "Mara"));
  check("nor when the departure is in a different sentence about somebody else", !showsDeparture("Mara put the cup down. The steward left.", "Mara"));
}

/* ── only witnesses learn ───────────────────────────────────────────────────────────────────── */
{
  const s = newGame({ seed: "test-witness", starting_slaves: 3 });
  const [a, , c] = Object.keys(s.people);
  s.scene.present = [a];
  applyDiff(s, { memories: [{ id: c, content: "heard the whole thing from the kitchen", importance: 7 }] }, "Nothing much happened.");
  check("a memory cannot be filed for somebody who was not in the room", (s.memory[c]?.episodic.length ?? 0) === 0);
  applyDiff(s, { memories: [{ id: a, content: "what was actually said", importance: 7 }] }, "Nothing much happened.");
  check("and it can for somebody who was", (s.memory[a]?.episodic.length ?? 0) === 1);
}

/* ── the detectors ──────────────────────────────────────────────────────────────────────────── */
{
  const s = newGame({ seed: "test-detect", starting_slaves: 1 });
  const name = s.people[Object.keys(s.people)[0]].name;
  check("an interior the narrator was not given is caught",
    !!findInteriorLeak(`${name} felt the whole thing settle into place.`, s));
  check("and its nicer coat is caught too",
    !!findInteriorLeak("Something tightened behind her eyes.", s));
  check("dialogue is not a violation",
    !findInteriorLeak(`"I knew you would say that," she said.`, s));
  check("a maxim is caught", !!findMaxim(`She shrugged. "People always want what they cannot have."`));
  check("an ordinary line is not", !findMaxim(`She shrugged. "I told you already, I am not doing it."`));
  check("the narrator handing your own line back is caught",
    !!findEcho("You tell her to get out of the room. She does not move.", "you tell her to get out of the room"));
}

/* ── the rules engine ───────────────────────────────────────────────────────────────────────── */
{
  const s = newGame({ seed: "test-rules", starting_slaves: 4 });
  for (const p of Object.values(s.people)) { p.health.health = -60; refresh(p, s.memory[p.id]); }
  const order = s.orders.find((o) => o.id === "o-health")!;

  const before = JSON.stringify(s.people);
  const shown = preview(s, order);
  check("the dry run finds who it would touch", shown.length === 4, shown.length);
  check("and changes absolutely nothing", JSON.stringify(s.people) === before);

  const ran = runOrders(s, false);
  check("running it for real does change them", ran.length > 0 && Object.values(s.people).every((p) => p.health.curatives === 1));
  check("and the person records which rule did it", Object.values(s.people).every((p) => p.rules_applied.includes("o-health")));
  check("a rule renders as a sentence", /^When .* — /.test(describe(order)), describe(order));
}

/* ── doctrine scoring ───────────────────────────────────────────────────────────────────────── */
{
  const s = newGame({ seed: "test-doctrine", starting_slaves: 1 });
  const p = Object.values(s.people)[0];
  p.body.boobs = 1600;
  p.body.butt = 8;
  const expansionist = scoreFor(p, DOCTRINE_BY_ID["expansionist"]);
  const slim = scoreFor(p, DOCTRINE_BY_ID["slimness"]);
  check("opposed doctrines read the same body in opposite directions", expansionist > 0.3 && slim < -0.3, { expansionist, slim });
  check("the axes are bounded", Object.values(axesOf(p)).every((v) => v >= -1 && v <= 1));

  adoptDoctrine(s, "expansionist");
  const clash = adoptDoctrine(s, "slimness");
  check("and they cannot be held at the same time", !clash.ok, clash);
  check("the arcology can explain its opinion of a person", explainFor(s, p).length > 0, explainFor(s, p));
}

/* ── the generator ──────────────────────────────────────────────────────────────────────────── */
{
  const a = generatePerson({ seed: "same" });
  const b = generatePerson({ seed: "same" });
  check("the same seed makes the same person", a.name === b.name && a.body.height_cm === b.body.height_cm && a.psyche.capacity_born === b.psyche.capacity_born);
  const c = generatePerson({ seed: "different" });
  check("a different seed does not", a.name !== c.name || a.body.height_cm !== c.body.height_cm);

  const many = Array.from({ length: 60 }, (_, i) => generatePerson({ seed: `spread:${i}` }));
  const styles = new Set(many.map((p) => p.persona.attachment.style));
  check("temperaments spread rather than clustering on one", styles.size >= 3, [...styles]);
  const capacities = many.map((p) => p.psyche.capacity_born);
  check("resting points vary", Math.max(...capacities) - Math.min(...capacities) > 3);
  check("everybody arrives with a body described in words", many.every((p) => p.body.appearance_facts.length > 20));
}

/* ── conception ─────────────────────────────────────────────────────────────────────────────── */
{
  const s = newGame({ seed: "test-preg", starting_slaves: 2 });
  const [a, b] = Object.values(s.people);
  a.womb.sterile = false;
  a.womb.fertility = 100;
  a.womb.cycle_day = 14;
  a.womb.contraceptives = true;
  let got = 0;
  for (let i = 0; i < 200; i++) if (tryConception(s, a, b.id, 6)) got++;
  check("contraceptives are absolute", got === 0);

  a.womb.contraceptives = false;
  a.womb.cycle_day = 2;
  let outside = 0;
  for (let i = 0; i < 300; i++) { if (tryConception(s, a, b.id, 6)) { outside++; a.womb.fetuses = []; } }
  a.womb.cycle_day = 14;
  let inside = 0;
  for (let i = 0; i < 300; i++) { if (tryConception(s, a, b.id, 6)) { inside++; a.womb.fetuses = []; } }
  check("the fertile window is a real window", inside > outside * 3, { inside, outside });
}

/* ── managers do something, including the wrong thing ──────────────────────────────────────── */
{
  const s = newGame({ seed: "test-managers", starting_slaves: 4 });
  s.arcology.facilities["brothel"].level = 1;
  s.arcology.facilities["brothel"].capacity = 4;
  const [boss, worker] = Object.values(s.people);
  assignToFacility(s, boss, "brothel");
  assignToFacility(s, worker, "brothel");
  s.arcology.facilities["brothel"].manager = boss.id;

  // A manager under the post's floor sabotages, and it shows up as money rather than as flavour.
  boss.bond = { ...boss.bond, bond: -40, fear: 0, resentment: 70, hope: 0 };
  refresh(boss, s.memory[boss.id]);
  const cashBefore = s.arcology.cash;
  const bad = runManager(s, "brothel");
  check("a manager who hates you costs you money", s.arcology.cash < cashBefore, { before: cashBefore, after: s.arcology.cash });
  check("and it is reported rather than silent", bad.lines.length > 0 && bad.income < 1, bad.lines.map((l) => l.text));

  // A good one is worth having.
  boss.bond = { ...boss.bond, bond: 80, fear: 5, resentment: 0, hope: 60 };
  boss.skills.management.madam = 70;
  refresh(boss, s.memory[boss.id]);
  const good = runManager(s, "brothel");
  check("a good manager raises what the room earns", good.income > 1.2, good.income);
  check("and trains the people in it faster", good.training > 1.2, good.training);
}

/* ── policies, and the doctrine that will not have them ────────────────────────────────────── */
{
  const s = newGame({ seed: "test-policy", starting_slaves: 2 });
  s.arcology.cash = 100000;
  check("a policy can be enacted", enact(s, "curfew").ok);
  check("and not twice", !enact(s, "curfew").ok);
  adoptDoctrine(s, "paternalist");
  s.arcology.doctrines["paternalist"].adoption = 70;
  const refused = enact(s, "public_punishment");
  check("a doctrine your citizens hold refuses the policy that contradicts it", !refused.ok, refused);

  // Hope-bearing policies actually reach the household.
  const before = Object.values(s.people).map((p) => p.bond.hope);
  enact(s, "manumission");
  const led = new Ledger();
  tickPolicies(s, led);
  const after = Object.values(s.people).map((p) => p.bond.hope);
  check("a published price at which she could buy herself out reaches her", after.every((h, i) => h > before[i]), { before, after });
}

/* ── unrest is not security, and the difference is the point ───────────────────────────────── */
{
  const s = newGame({ seed: "test-unrest", starting_slaves: 4 });
  for (const p of Object.values(s.people)) {
    p.bond.resentment = 90;
    p.bond.hope = 0;
    p.bond.bond = -50;
    refresh(p, s.memory[p.id]);
  }
  const high = unrest(s);
  check("a household carrying that much reads as unrest", high > 50, high);
  s.arcology.security = 100;
  check("and maximum security does absolutely nothing to it", Math.abs(unrest(s) - high) < 0.01);
  for (const p of Object.values(s.people)) { p.bond.resentment = 0; p.bond.hope = 70; p.bond.bond = 50; refresh(p, s.memory[p.id]); }
  check("what moves it is what the people are carrying", unrest(s) < 20, unrest(s));
}

/* ── every event can fire ──────────────────────────────────────────────────────────────────────
 * Events are the most crash-prone code in a sim like this: each one reaches into a different
 * corner of the state, and the corner is usually empty on the week it finally fires. So every
 * option of every event is resolved against a real save, once.
 */
{
  let threw: unknown = null;
  let fired = 0;
  for (const def of EVENTS) {
    for (const opt of def.options) {
      const s = newGame({ seed: `test-event-${def.id}-${opt.id}`, starting_slaves: 4 });
      s.arcology.cash = 80000;
      const person = Object.values(s.people)[0];
      const e = {
        id: "x", kind: def.id, person: person.id, seed: "", options: [],
        week: s.arcology.week, severity: def.severity,
      };
      try { opt.resolve(s, e, person); fired++; } catch (err) { threw = `${def.id}/${opt.id}: ${String(err)}`; }
    }
  }
  check(`every option of every event resolves (${fired})`, !threw, threw);
  check("and the pressure controller stays in range", (() => {
    const s = newGame({ seed: "test-pressure", starting_slaves: 3 });
    const p = pressure(s);
    return p >= 0 && p <= 12;
  })());
}

/* ── the age gate, and the clock ─────────────────────────────────────────────────────────────
 * Births produce children, and the moment children exist every assignment dropdown in the app will
 * offer them to the brothel. The gate is in the engine, on the one writer, so a rules effect and a
 * facility move and a hand edit all hit it.
 */
{
  const s = newGame({ seed: "test-minor", starting_slaves: 1 });
  const child = generatePerson({ seed: "child", age: 18, week: 1 });
  child.age = 9;
  child.birth_week = s.arcology.week - 9 * 52;
  s.people[child.id] = child;
  s.memory[child.id] = newMemory();

  check("a child is a minor", isMinor(child));
  check("and cannot be assigned to the work", !!setAssignment(s, child, "whore") && child.assignment !== "whore");
  check("nor moved into a facility that is not for her", (() => {
    s.arcology.facilities["brothel"].level = 1;
    s.arcology.facilities["brothel"].capacity = 4;
    assignToFacility(s, child, "brothel");
    return child.facility !== "brothel";
  })());
  check("the nursery is allowed", (() => {
    s.arcology.facilities["nursery"].level = 1;
    s.arcology.facilities["nursery"].capacity = 4;
    assignToFacility(s, child, "nursery");
    return child.facility === "nursery";
  })());
  check("a standing order cannot route around it", (() => {
    s.orders.push({ id: "o-test", name: "everyone whores", enabled: true, priority: 1, conditions: [], effects: [{ field: "assignment", value: "whore" }] });
    runOrders(s, false);
    return child.assignment !== "whore";
  })());
  check("and the picker offers her only what she may do",
    allowedAssignments(child, ["rest", "whore", "classes"]).join() === "rest,classes");

  // Time passes for adults too — only children aged, which is the bug you do not notice for a
  // hundred weeks and then cannot unsee.
  const grown = Object.values(s.people).find((p) => p.age >= 18)!;
  const wasAge = grown.age;
  grown.birth_week = s.arcology.week - wasAge * 52;
  s.arcology.week += 52;
  tickAge(s, grown);
  check("adults age on the same clock as everybody else", grown.age === wasAge + 1, { was: wasAge, now: grown.age });
}

/* ── the player's own skills are not decoration ─────────────────────────────────────────────
 * Five numbers were listed on a screen with a sentence each describing what they did, and nothing
 * in the engine read four of them. A skill with a description and no reader is a lie told in the
 * interface, so each one is asserted against the place that reads it.
 */
{
  const s = newGame({ seed: "test-skills", starting_slaves: 2 });
  s.player.skills = { trading: 0, slaving: 0, medicine: 0, engineering: 0, hacking: 0 };
  const base = { trading: skill.trading(s), slaving: skill.slaving(s), medicine: skill.medicine(s), engineering: skill.engineering(s) };
  s.player.skills = { trading: 100, slaving: 100, medicine: 100, engineering: 100, hacking: 100 };
  check("trading buys people cheaper", skill.trading(s) < base.trading);
  check("slaving trains them faster", skill.slaving(s) > base.slaving);
  check("medicine makes surgery cost them less", skill.medicine(s) < base.medicine);
  check("engineering makes building cheaper", skill.engineering(s) < base.engineering);
  check("hacking shows you what the neighbours are running", skill.hacking(s) && !skill.hacking({ ...s, player: { ...s.player, skills: {} } } as typeof s));

  practise(s, "medicine", 5);
  check("and practice is capped rather than unbounded", (s.player.skills.medicine ?? 0) <= 100);
}

/* ── facility membership has one writer ─────────────────────────────────────────────────────── */
{
  const s = newGame({ seed: "test-facility", starting_slaves: 3 });
  s.arcology.facilities["spa"].level = 1;
  s.arcology.facilities["spa"].capacity = 1;
  const [a, b] = Object.values(s.people);
  assignToFacility(s, a, "spa");
  assignToFacility(s, b, "spa");
  check("a full facility refuses the next body", s.arcology.facilities["spa"].workers.length === 1);
  check("and the person is not left pointing at it", b.facility === undefined);
  assignToFacility(s, a, undefined);
  check("leaving a facility clears both sides", !s.arcology.facilities["spa"].workers.length && a.facility === undefined);
}
